@startuml care-services-use-case-2

skinparam roundcorner 20
skinparam defaultFontName Arial 
hide footbox

!pragma teoz true

actor  Doctor as "Dr. West"
participant  EHR as "EHR"
participant  CSD as "Query Directory"
participant  EHR2 as "Endpoint supporting\nTransfer of care\n@Hospital East"


activate Doctor
activate EHR
group create referral 
 Doctor -> EHR: create referral for Dr. East\n for Orthopedic department\n at Hospital East
end
activate CSD
EHR -> CSD: Find HealthcareService of Orthopedic department\n including Endpoints
EHR -> EHR: Check Endpoints for 'Transfer of care' support
EHR -> CSD: If no endpoint found: find Organization of HealthcareService\n including Endpoint
EHR -> EHR: Check Endpoints for 'Transfer of care' support
loop If no endpoint found and\nOrganization is part of parent Organization
    EHR -> CSD: Find parent Organization of Organization\n including Endpoints
    EHR -> EHR: Check Endpoints for 'Transfer of care' support
end
deactivate CSD
EHR -> EHR2: Post **notification** to Endpoint\nof Hospital East with referral ID
group referral response
 EHR2 -> EHR: Respond to referral
 & EHR -> Doctor: Handle referral response
end

deactivate Doctor
deactivate EHR
@enduml
