@startuml care-services-use-case-1

skinparam roundcorner 20
skinparam defaultFontName Arial 
hide footbox

!pragma teoz true

actor  Patient as "Vera"
actor  Doctor as "Dr. West"
participant  EHR as "EHR (Query Client)"
participant  CSD as "Query Directory"

activate Patient
activate Doctor
Patient -> Doctor: My knee hurts
Doctor -> Doctor: diagnosis = torn ACL
activate EHR
Doctor -> EHR: use EHR's custom query tool \nsearch for orthopedic services, \nwithin 30km of Vera's home
activate CSD
EHR-> CSD: Find Matching Care Services request\n GET [base]/HealthcareService?\ntype=consultation\n&specialty=orthopedics
CSD -> EHR: response
EHR-> CSD: Get (parent) Organizations and Locations for HealthcareServices\n GET /Organization/[id], GET /Location/[id], etc
CSD -> EHR: response
EHR -> EHR: Filter results on distance to Vera's home
deactivate CSD
EHR -> Doctor : Review results\nwith office address, hours of operation
Doctor -> Patient: Review and discuss options
deactivate Patient
deactivate Doctor
deactivate EHR
@enduml
