@startuml localization-cardiologist-search

skinparam roundcorner 20
skinparam defaultFontName Arial 
hide footbox

!pragma teoz true

actor "Dr. Smith\n(Cardiologist)" as doctor
participant "EHR System @\n(Care Provider, URA:456)" as ehr
participant "Localization Service" as nvi
participant "EHR @\n(Care Provider, URA:123)" as ehr_reg

doctor -> ehr: Request data\n for patient (BSN:987654321)

note over nvi
  Required authorization attributes for GET:
  - Organization Identifier (URA:456)
  - OrganizationType: 2.16.840.1.113883.2.4.15.1060|V4 (Hospital)
  - Practitioner Identifier: Dr. Smith's UZI/DEZI 
  - Role code: Professional role code (e.g., cardiologist)
  ' Use of **pseudonymized** patient identifier 
  '  (pseudoBsn) is out of scope for this diagram
end note

ehr -> nvi: GET DocumentReference, where:\n Bsn=987654321



nvi -> nvi: Validate authorization\nand search data locations

nvi -> ehr: Return response with data locations:\n[\n  {subject: "BSN:987654321",\n custodian: "URA-123", ...},\n  {...},\n  {...}\n]


ehr -> ehr: Get FHIR URLs for\n care provider URA:123

ehr -> ehr_reg: Query FHIR endpoint for patient (BSN:987654321)

ehr -> doctor: Display available encounters\n and conditions to Dr. Smith

@enduml
